name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm i -g npm@7
      - run: npm ci
      - run: npm run build

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm i -g npm@7
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm i -g npm@7
      - run: npm ci
      - run: npm run test-no-progress
      - run: npm run report-coverage

  tsd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm i -g npm@7
      - run: npm ci
      - run: npm run tsd
